export const ReduxActionTypes = {
  APP_LOADER: "APP_LOADING",
  FETCH_LOCATIONS: "FETCH_LOCATIONS",
  UPDATE_LATEST_PLACES: "UPDATE_LATEST_PLACES",
  CLEAR_PLACES: "CLEAR_PLACES",

  FETCH_HOTELS_LIST: "FETCH_HOTELS_LIST",
  FETCH_HOTELS_OF_LOCATION: "FETCH_HOTELS_OF_LOCATION",
  UPDATE_HOTELS_OF_LOCATION: "UPDATE_HOTELS_OF_LOCATION",
  UPDATE_LATEST_HOTELS_LIST: "UPDATE_LATEST_HOTELS_LIST",
  CLEAR_HOTELS_LIST: "CLEAR_HOTELS_LIST",

  FETCH_SINGLE_HOTEL: "FETCH_SINGLE_HOTEL",
  UPDATE_SINGLE_HOTEL: "UPDATE_SINGLE_HOTEL",
};
